import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import API from "../services/api";
import { getProjects, createProject, updateProject, deleteProject } from "../services/projectService";
import { getTasks, createTask, updateTask, deleteTask, updateTaskStatus } from "../services/taskService";

const emptyProject = { title: "", description: "", assignedMembers: [] };
const emptyTask = { title: "", description: "", project: "", assignedTo: "", status: "Pending", priority: "Medium", dueDate: "" };
const input = "w-full rounded-lg border border-slate-300 p-2 focus:outline-none focus:ring-2 focus:ring-blue-500";
const message = (error) => error.response?.data?.message || "Unable to connect to server. Please try again.";

export default function Dashboard() {
  const navigate = useNavigate();
  const [user] = useState(() => JSON.parse(localStorage.getItem("user") || "null"));
  const admin = user?.role === "Admin";
  const [projects, setProjects] = useState([]), [tasks, setTasks] = useState([]), [members, setMembers] = useState([]);
  const [projectForm, setProjectForm] = useState(emptyProject), [taskForm, setTaskForm] = useState(emptyTask);
  const [projectId, setProjectId] = useState(null), [taskId, setTaskId] = useState(null), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const load = async () => { try { const [p, t] = await Promise.all([getProjects(), getTasks()]); setProjects(p.data); setTasks(t.data); if (admin) setMembers((await API.get("/users/members")).data); } catch (err) { setError(message(err)); } };
  useEffect(() => { if (!user || !localStorage.getItem("token")) navigate("/login"); else load(); }, []);
  const saveProject = async (e) => { e.preventDefault(); try { const editing = Boolean(projectId); await (editing ? updateProject(projectId, projectForm) : createProject(projectForm)); setProjectForm(emptyProject); setProjectId(null); setSuccess(editing ? "Project updated successfully" : "Project created successfully"); load(); } catch (err) { setError(message(err)); } };
  const saveTask = async (e) => { e.preventDefault(); try { const editing = Boolean(taskId); await (editing ? updateTask(taskId, taskForm) : createTask(taskForm)); setTaskForm(emptyTask); setTaskId(null); setSuccess(editing ? "Task updated successfully" : "Task created successfully"); load(); } catch (err) { setError(message(err)); } };
  const selectProject = (project) => { setProjectId(project._id); setProjectForm({ title: project.title, description: project.description, assignedMembers: project.assignedMembers || [] }); };
  const selectTask = (task) => { setTaskId(task._id); const p = projects.find((project) => project.title === task.project); setTaskForm({ ...task, project: p?._id || "", dueDate: task.dueDate?.slice(0, 10) || "" }); };
  const stats = (status) => tasks.filter((task) => task.status === status).length;
  const overdue = tasks.filter((task) => task.dueDate && new Date(task.dueDate) < new Date(new Date().toDateString()) && task.status !== "Completed").length;
  const toggleMember = (email) => setProjectForm((form) => ({ ...form, assignedMembers: form.assignedMembers.includes(email) ? form.assignedMembers.filter((item) => item !== email) : [...form.assignedMembers, email] }));
  if (!user) return null;
  return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><header className="mb-6 flex items-center justify-between rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 p-6 text-white"><div><h1 className="text-3xl font-bold">Team Task Dashboard</h1><p>Welcome {user.name} ({user.role})</p></div><button onClick={() => { localStorage.removeItem("token"); localStorage.removeItem("user"); navigate("/login"); }} className="rounded bg-white px-4 py-2 font-semibold text-slate-800">Logout</button></header>
    {error && <p className="mb-4 rounded bg-red-100 p-3 text-red-700">{error}</p>}{success && <p className="mb-4 rounded bg-emerald-100 p-3 text-emerald-700">{success}</p>}<section className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[["Pending Tasks", stats("Pending"), "bg-amber-400"], ["Completed Tasks", stats("Completed"), "bg-emerald-500 text-white"], ["In Progress", stats("In Progress"), "bg-blue-500 text-white"], ["Overdue Tasks", overdue, "bg-red-500 text-white"]].map(([label, count, color]) => <div key={label} className={`${color} rounded-xl p-4 shadow`}><b className="text-3xl">{count}</b><p>{label}</p></div>)}</section>
    {admin && <section className="mb-6 rounded-2xl bg-white p-6 shadow"><h2 className="mb-4 text-2xl font-bold">{projectId ? "Edit Project" : "Create Project"}</h2><form onSubmit={saveProject} className="space-y-3"><input required className={input} placeholder="Project Title" value={projectForm.title} onChange={(e) => setProjectForm({ ...projectForm, title: e.target.value })}/><textarea required className={input} placeholder="Project Description" value={projectForm.description} onChange={(e) => setProjectForm({ ...projectForm, description: e.target.value })}/><div><b>Assign Members</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{members.map((member) => <label key={member._id} className="flex items-center gap-2"><input type="checkbox" checked={projectForm.assignedMembers.includes(member.email)} onChange={() => toggleMember(member.email)}/>{member.email}</label>)}</div></div><button className="rounded bg-blue-600 px-4 py-2 text-white">{projectId ? "Save Project" : "Create Project"}</button>{projectId && <button type="button" onClick={() => { setProjectId(null); setProjectForm(emptyProject); }} className="ml-2 rounded bg-slate-200 px-4 py-2">Cancel</button>}</form></section>}
    <section className="mb-6 rounded-2xl bg-white p-6 shadow"><h2 className="mb-4 text-2xl font-bold">{admin ? "All Projects" : "Your Assigned Projects"}</h2><div className="grid gap-4 md:grid-cols-2">{projects.map((project) => <article key={project._id} className="rounded-xl border p-4"><h3 className="text-xl font-bold">{project.title}</h3><p>{project.description}</p><p className="mt-2 text-sm"><b>Assigned Members:</b> {project.assignedMembers?.join(", ") || "None"}</p>{admin && <p className="mt-3"><button onClick={() => selectProject(project)} className="mr-3 text-blue-700">Edit</button><button onClick={async () => { if (confirm("Are you sure you want to delete this project?")) { try { await deleteProject(project._id); setSuccess("Project deleted successfully"); load(); } catch (err) { setError(message(err)); } } }} className="text-red-600">Delete</button></p>}</article>)}</div></section>
    {admin && <section className="mb-6 rounded-2xl bg-white p-6 shadow"><h2 className="mb-4 text-2xl font-bold">{taskId ? "Edit Task" : "Create Task"}</h2><form onSubmit={saveTask} className="space-y-3"><input required className={input} placeholder="Task Title" value={taskForm.title} onChange={(e) => setTaskForm({ ...taskForm, title: e.target.value })}/><textarea className={input} placeholder="Description" value={taskForm.description} onChange={(e) => setTaskForm({ ...taskForm, description: e.target.value })}/><select required className={input} value={taskForm.project} onChange={(e) => setTaskForm({ ...taskForm, project: e.target.value })}><option value="">Select Project</option>{projects.map((project) => <option key={project._id} value={project._id}>{project.title}</option>)}</select><select required className={input} value={taskForm.assignedTo} onChange={(e) => setTaskForm({ ...taskForm, assignedTo: e.target.value })}><option value="">Assign Member</option>{members.map((member) => <option key={member._id} value={member.email}>{member.email}</option>)}</select><div className="grid grid-cols-2 gap-3"><select className={input} value={taskForm.status} onChange={(e) => setTaskForm({ ...taskForm, status: e.target.value })}><option>Pending</option><option>In Progress</option><option>Completed</option></select><select className={input} value={taskForm.priority} onChange={(e) => setTaskForm({ ...taskForm, priority: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></div><input required type="date" className={input} value={taskForm.dueDate} onChange={(e) => setTaskForm({ ...taskForm, dueDate: e.target.value })}/><button className="rounded bg-purple-600 px-4 py-2 text-white">{taskId ? "Save Task" : "Create Task"}</button>{taskId && <button type="button" onClick={() => { setTaskId(null); setTaskForm(emptyTask); }} className="ml-2 rounded bg-slate-200 px-4 py-2">Cancel</button>}</form></section>}
    <section className="rounded-2xl bg-white p-6 shadow"><h2 className="mb-4 text-2xl font-bold">{admin ? "All Tasks" : "Your Tasks"}</h2>{tasks.map((task) => <article key={task._id} className="mb-3 rounded-xl border p-4"><b>{task.title}</b><p>{task.description}</p><p>Project: {task.project} | Assigned: {task.assignedTo}</p><p>Priority: {task.priority} | Due: {new Date(task.dueDate).toLocaleDateString()}</p>{admin ? <p><span>Status: {task.status}</span><button onClick={() => selectTask(task)} className="ml-3 text-blue-700">Edit</button><button onClick={async () => { if (confirm("Are you sure you want to delete this task?")) { try { await deleteTask(task._id); setSuccess("Task deleted successfully"); load(); } catch (err) { setError(message(err)); } } }} className="ml-3 text-red-600">Delete</button></p> : <label>Status: <select value={task.status} onChange={async (e) => { try { await updateTaskStatus(task._id, e.target.value); setSuccess("Task status updated successfully"); load(); } catch (err) { setError(message(err)); } }} className="ml-2 border p-1"><option>Pending</option><option>In Progress</option><option>Completed</option></select></label>}</article>)}</section>
  </main>;
}
